### ISSUE TITLE
Issue during conversion.

### ISSUE THREAD

**Issue by isspid** [Taeyoung96/Yolo-to-COCO-format-converter#10]
I am getting this json file as an output:
![image](https://user-images.githubusercontent.com/91065022/148397638-f446945f-bf08-4cf0-b6e2-f02e72280bc2.png)

This is my CLI command:
![image](https://user-images.githubusercontent.com/91065022/148397678-513e0618-d8e2-4489-8f6a-41db05eec7e7.png)

Do you know how I could fix this?

**Comment by Taeyoung96** [comment]
Hi @isspid, 
Could you explain more about this problem?  
When I get more information about the problem, I will give you the right solution.

In your path `C:\Users\istaka\Downolads\window\obj_train_data`, what files are in it?  

Do you have both Image and .txt files?  

What kind of annotation tool did you use it?  

Thanks,

**Comment by stevengnow** [comment]
Make sure you are reading the images as ".jpg". If your images are in a different format or as ".JPG" then it will not read in the images.
