### ISSUE TITLE
All files not converted

### ISSUE THREAD

**Issue by mazaaaa** [Taeyoung96/Yolo-to-COCO-format-converter#18]
This is not converting all the files to COCO its skipping some, please check

**Comment by Taeyoung96** [comment]
@mazaaaa   
Hi, Have you tried running the example in the tutorial folder?  
You should be able to do this algorithm correctly, assuming you have all your images annotated.  

Or can you be more specific about the situation where the skip happens?

**Comment by mazaaaa** [comment]
Hey, it actually worked out later after the initial errors. Thanks.
