### ISSUE TITLE
A bug with multi-annotations on a image

### ISSUE THREAD

**Issue by ginvu2005** [Taeyoung96/Yolo-to-COCO-format-converter#23]
Thank you for your contribution. I think there is a bug [here]( https://github.com/Taeyoung96/Yolo-to-COCO-format-converter/blob/b51e420803359256fc0446c9817d0af2ad651a25/main.py#L111). "annotation_id" should increase after new annotation append to annotation list. I got problem when I use pycocotools to debug, they just show the last annotation because annotation_id is not unique.

**Comment by Taeyoung96** [comment]
@kytaithon   
Hi, Thanks for finding the bug!  
Can you describe in a little more detail what you were troubled with the `annotation_id`?

**Comment by ginvu2005** [comment]
Hi @Taeyoung96, I think `annotation_id` should inside the [second for loop](https://github.com/Taeyoung96/Yolo-to-COCO-format-converter/blob/b51e420803359256fc0446c9817d0af2ad651a25/main.py#L67). For some datasets which have multiple bbox in a image this will cause missing label when people use pycocotools to load datasets (pycocotool don't get diffirent `annotation_id` for diffirent bbox).

**Comment by Taeyoung96** [comment]
@kytaithon 
Understood, please provide a PR with the bug fixed and I'll merge it. :+1:
