### ISSUE TITLE
What if there is no ".txt" file for some images?

### ISSUE THREAD

**Issue by Rajat-Mehta** [Taeyoung96/Yolo-to-COCO-format-converter#7]
hi,

What if there is no ".txt" file for some images, which can happen in YOLO format datasets? I tried it with my dataset and the conversion script was not able to handle it.
```
Start!
Processing 0 ...
Traceback (most recent call last):
  File "main.py", line 161, in <module>
    coco_format['images'], coco_format['annotations'] = images_annotations_info(opt)
  File "main.py", line 43, in images_annotations_info
    label_file = open(label_path,"r")

```

**Comment by Taeyoung96** [comment]
@Rajat-Mehta Hi,  
This repository was created assuming all txt files exist,  
so if there is no txt file, you need to handle an exception yourself. 😥

**Comment by Rajat-Mehta** [comment]
Thanks for your answer. I am handling it manually now.

**Comment by kb1ooo** [comment]
It looks like this is somewhat handled now.  However, I believe that there is a bug.  The imageid does not get incremented if there is no label file (continue at line 86 of main.py, which skips the image_id increment at line 126).

**Comment by Taeyoung96** [comment]
@kb1ooo   
Hi,  
Could you give me some detail about the bug?  
In this repository, I didn't update about handling exceptions.

**Comment by kb1ooo** [comment]
@Taeyoung96 I'm not sure what you mean exactly by "exceptions", but the coco format supports images that do not have annotations, which some algorithms are able to treat as "negative" images.  The code currently adds such images to the image array.  However, it does not increment the `image_id` in that case, because if there is no label file, the `continue` statement on line 86 of `main.py` ends up skipping the `image_id` increment at line 126.   Here is a resulting json from three images `a.jpg`, `b.jpg`, and `c.jpg` where only `a.jpg` has a corresponding `.txt` label file.   You can see that both images `b.jpg` and `c.jpg` get the same `image_id`.

```
{
    "images": [
        {
            "file_name": "a.jpg",
            "height": 512,
            "width": 640,
            "id": 0
        },
        {
            "file_name": "b.jpg",
            "height": 512,
            "width": 640,
            "id": 1
        },
        {
            "file_name": "c.jpg",
            "height": 512,
            "width": 640,
            "id": 1
        }
    ],
    "categories": [
        {
            "supercategory": "Defect",
            "id": 1,
            "name": "sedan"
        },
        {
            "supercategory": "Defect",
            "id": 2,
            "name": "hatchback"
        }
    ],
    "annotations": [
        {
            "id": 1,
            "image_id": 0,
            "bbox": [
                342.5,
                312.0,
                43.0,
                30.0
            ],
            "area": 1290,
            "iscrowd": 0,
            "category_id": 2,
            "segmentation": []
        }
    ]
}
```

**Comment by kb1ooo** [comment]
I will add that a simple fix would be to just add an `image_id` increment before the continue.  
```
85         if not annotations_path.exists():
86             image_id += 1 
87             continue           # The image may not have any applicable annotation txt file.
```

**Comment by Taeyoung96** [comment]
@kb1ooo   
When I said exception handling, I was talking about the case where it is not annotated as mentioned in this issue.  
I think your idea can fix the bug when there is no annotation file.  
If you don't mind would you give me PR?
